httpPort: 13000
appName: connector
log:
  level: DEBUG
db:
  redis:
    addr: 119.28.81.104:6379
    poolSize: 10
    minIdleConns: 1
    password: CAW7qv1i0Pss
jwt:
  secret: 123456
  exp: 7
domain:
  user:
    name: user/v1
    loadBalance: true
etcd:
  addrs:
    - 127.0.0.1:2379
  rwTimeout: 3
  dialTimeout: 3
services:
  connector:
    id: connector-1
    clientHost: 127.0.0.1
    clientPort: 12000